# Generated by Django 5.0.3 on 2024-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigimonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_digimon', models.CharField(max_length=25, verbose_name='Nome')),
                ('tipo_digimon', models.CharField(max_length=10, verbose_name='Tipo')),
                ('atributo_digimon', models.CharField(max_length=15, verbose_name='Atributo')),
                ('level_digimon', models.CharField(max_length=15, verbose_name='Level')),
            ],
        ),
    ]
