# Generated by Django 5.0.3 on 2024-03-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digimonApp', '0003_remove_digimonmodel_imagem_digimon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digimonmodel',
            old_name='nome_digimon',
            new_name='name',
        ),
    ]
