# Generated by Django 5.0.3 on 2024-03-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digimonApp', '0004_rename_nome_digimon_digimonmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='digimonmodel',
            name='imagem_digimon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='digimonmodel',
            name='level_digimon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Level'),
        ),
    ]
